spring:
  datasource:
    username: admin
    password: OmSai@12345
    url: jdbc:mysql://prasadsanap:3306/db_perfect_resume
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  log:
    level: debug
  mail:
    host: smtp.gmail.com
    port: 587
    username: sanapprasad2021@gmail.com
    password: otrgwusrmdkigijr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

schedule:
  reset-otp: EXPIRED-OTP
  interval: 2
  stamp: MINUTE